Update various things

diff --git a/pwbunny b/pwbunny
--- a/pwbunny
+++ b/pwbunny
@@ -8,8 +8,18 @@
 # See below for full copyright
 #
 
-usage="Usage: $(basename "$0") [-c entryname] [FILE]"
 version="1.1"
+
+usage() {
+	echo "Usage: $(basename "$0") [-v] [-s file] [-c entryname] [file]"
+	echo
+	echo "  -h     Show this help"
+	echo "  -v     Show version and exit"
+	echo "  -c     TODO"
+	echo "  -s     Specify location of pwbunny.vim; defaults to TODO"
+	echo "  file   File to open, defaults to TODO"
+	echo
+}
 
 getpw=""
 pwname=""
@@ -17,10 +27,13 @@ while getopts ":c:hv" option; do
 	case $option in
 		c)
 			getpw=1
-			pwname=$OPTARG
+			pwname="$OPTARG"
+			;;
+		s)
+			vimfile="$OPTARG"
 			;;
 		h)
-			echo "$usage"
+			usage
 			exit 0
 			;;
 		v)
@@ -28,7 +41,7 @@ while getopts ":c:hv" option; do
 			exit 0
 			;;
 		?)
-			echo "$usage" >&2
+			usage
 			exit 2
 			;;
 	esac
@@ -39,9 +52,18 @@ getpwarg=""
 [ ! -z "$getpw" ] && getpwarg="| call PwbunnyFindCopyClose('"$pwname"')"
 
 me=$(basename "$0")
-root=$(dirname "$(readlink -f "$me")")
-file="$root/passwords.pwbunny"
-[ ! -z "$1" ] && file="$1"
+root=$(dirname "$(readlink -f "$0")")
+if [ ! -z "$1" ]; then
+	file="$1"
+elif [ -f "$HOME/.pwbunny/passwords.pwbunny" ]; then
+	file="$HOME/.pwbunny/passwords.pwbunny"
+elif [ -f "$root/passwords.pwbunny" ]; then
+	file="$root/passwords.pwbunny"
+else
+	file="$HOME/.pwbunny/passwords.pwbunny"
+fi
+
+mkdir -p "$(dirname "$file")"
 
 args=""
 [ "$me" = gpwbunny ] && args=" -g --nofork "
@@ -64,8 +86,24 @@ elif [ "$(head -c12 "$file")" = "VimCrypt~01!" ]; then
 	echo
 	echo "Press enter to continue"
 	read x
+# cm=blowfish
+elif [ "$(head -c12 "$file")" == "VimCrypt~02!" ]; then
+	echo "WARNING"
+	echo "The file \`$file' uses cryptmethod=blowfish"
+	echo
+	echo "THIS IS NO LONGER SECURE!"
+	echo
+	echo "For details, see:"
+	echo "https://groups.google.com/d/msg/vim_dev/D8FyRd0EwlE/bkBOo-hzTzoJ"
+	echo 
+	echo "To properly encrypt this file, use:"
+	echo ":set cryptmethod=blowfish2"
+	echo ":w"
+	echo
+	echo "Press enter to continue"
+	read x
 # File doesn't seem to be encrypted
-elif [ "$(head -c12 "$file")" != "VimCrypt~02!" ]; then
+elif [ "$(head -c12 "$file")" != "VimCrypt~03!" ]; then
 	echo "WARNING"
 	echo "The file \`$file' doesn't seem to be encrypted"
 	echo
@@ -81,8 +119,29 @@ elif [ "$(head -c12 "$file")" != "VimCrypt~02!" ]; then
 	read x
 fi
 
+vimfiles="/usr/share/pwbunny/pwbunny.vim \
+	/usr/local/share/pwbunny/pwbunny.vim \
+	/usr/pkg/share/pwbunny/pwbunny.vim \
+	$root/pwbunny.vim"
+
+if [ -z "$vimfile" ]; then
+	for f in $vimfiles; do
+		if [ -f "$f" ]; then
+			vimfile="$f"
+			break
+		fi
+	done
+fi
+
+if [ -z "$vimfile" ]; then
+	echo "Unable to find pwbunny.vim" >&2
+	exit 3
+fi
+
 while :; do
-    vim $args -nc "source $root/pwbunny.vim $getpwarg" "$file"
+    vim $args -n \
+		-c "source $root/parsejson.vim | source $vimfile $getpwarg"  \
+		"$file"
 
 	[ $? -eq 0 ] && break
 
